version: "3"
services:
  referral-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
  bnext-referral-backend-server:
    build: .
    restart: always
    depends_on:
      - referral-db
    ports:
      - "${PORT}:${PORT}"
volumes:
  data:
